### ISSUE TITLE
cant build pokecrystal.gbc 

### ISSUE THREAD

**Issue by ForceFaction** [kanzure/pokecrystal#286]
hi 
i tried to build the rom as described in INSTALL.md but make fails with these messages http://pastebin.com/6pLgXiCf. maybe i missed something but help appreciated :)
thx in advance

**Comment by kanzure** [comment]
You are probably using python3 to run the source code. Please try using python2, or converting the source code to be python3-compatible.

**Comment by ForceFaction** [comment]
kk you are right. thx
