### ISSUE TITLE
Can't make pngs

### ISSUE THREAD

**Issue by Greatpriceman** [kanzure/pokecrystal#288]
I tried to convert the .lzs into pngs through the command "make pngs" and I got this error
$ make pngs
find . -iname "*.lz"      -exec python extras/pokemontools/gfx.py unlz {} +
Traceback (most recent call last):
  File "extras/pokemontools/gfx.py", line 8, in <module>
    import yaml
ImportError: No module named yaml
Makefile:77: recipe for target 'pngs' failed
make: *** [pngs] Error 1
Is there a module named "yaml" ?

**Comment by kanzure** [comment]
Run the command `pip install yaml`

**Comment by Greatpriceman** [comment]
Thank you
